apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: workload-vsphere-tkg2
  namespace: namespace1000
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: pacific-gold-storage-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi
      tkr:
        reference:
          name: v1.20.9---vmware.1-tkg.1.a4cee5b
    nodePools:
    - name: node-pool-1
      replicas: 2
      vmClass: best-effort-medium
      storageClass: pacific-gold-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 30Gi
      tkr:
        reference:
          name: v1.20.9---vmware.1-tkg.1.a4cee5b
  settings:
    storage:
      classes: ["pacific-gold-storage-policy"]
      defaultClass: pacific-gold-storage-policy
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["192.0.0.0/16"]
      services:
        cidrBlocks: ["198.51.100.0/24"]
