apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
        version: v1
    spec:
      containers:
      - name: weather
        image: wardviaene/http-echo
        env:
        - name: TEXT
          value: 'Weather: '
        - name: NEXT
          value: "rain:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: weather
spec:
  selector:
    app: weather
  ports:
  - name: http
    port: 8080
    targetPort: 8080
